import ReceiptImage from '@/components/ReceiptImage';
import { useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { format } from 'date-fns';
import { ar, enUS } from 'date-fns/locale';
import { BarChart3, Eye, FileText, Home, LogOut, Menu, MessageCircle, RefreshCw, Search, ShoppingCart, Users, X } from 'lucide-react';
import { supabase } from '@/integrations/supabase/client';
import { useLanguage } from '@/contexts/LanguageContext';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import LanguageSwitcher from '@/components/LanguageSwitcher';
import AnalyticsDashboard from '@/components/admin/AnalyticsDashboard';
import RenewalDetailsDialog from '@/components/admin/RenewalDetailsDialog';
import logoAsset from '@/assets/core-studio-wordlogo-white.svg';

interface Order { id:string; order_id:string; full_name:string; business_name:string; email:string; phone:string; whatsapp:string; subscription_status:string; project_status:string; website_status:string; start_date:string|null; renewal_date:string|null; receipt_url:string|null; created_at:string; payment_method:string|null; setup_fee:number; monthly_fee:number; addon_total:number; coupon_code:string|null; coupon_discount:number; website_requirements:string|null; }
interface Renewal { id:string; renewal_id:string; original_order_id:string; full_name:string; business_name:string; email:string; phone:string; whatsapp:string; renewal_fee:number; payment_method:string|null; receipt_url:string|null; coupon_code:string|null; coupon_discount:number; status:'pending'|'confirmed'|'rejected'; created_at:string; }
interface Lead { id:string; full_name:string; email:string; phone:string; whatsapp:string; message:string; status:string; created_at:string; }
type Tab='analytics'|'subscribers'|'renewals'|'leads';
type Detail={type:'order';value:Order}|{type:'renewal';value:Renewal}|null;

const WorkDashboard=()=>{
 const {isRTL,language}=useLanguage(); const navigate=useNavigate();
 const [tab,setTab]=useState<Tab>('analytics'); const [sidebarOpen,setSidebarOpen]=useState(false); const [orders,setOrders]=useState<Order[]>([]); const [renewals,setRenewals]=useState<Renewal[]>([]); const [leads,setLeads]=useState<Lead[]>([]); const [loading,setLoading]=useState(true); const [search,setSearch]=useState(''); const [receipt,setReceipt]=useState<string|null>(null); const [detail,setDetail]=useState<Detail>(null);
 const dateLocale=language==='ar'?ar:enUS;
 useEffect(()=>{const load=async()=>{setLoading(true);const[o,r,l]=await Promise.all([supabase.from('orders').select('*').order('created_at',{ascending:false}),supabase.from('renewals').select('*').order('created_at',{ascending:false}),supabase.from('leads').select('*').order('created_at',{ascending:false})]);setOrders((o.data as Order[]|null)??[]);setRenewals((r.data as Renewal[]|null)??[]);setLeads((l.data as Lead[]|null)??[]);setLoading(false)};void load()},[]);
 useEffect(()=>setSearch(''),[tab]);
 const q=search.trim().toLowerCase();
 const visibleOrders=useMemo(()=>orders.filter(i=>[i.order_id,i.full_name,i.business_name,i.email].some(v=>v.toLowerCase().includes(q))),[orders,q]);
 const visibleRenewals=useMemo(()=>renewals.filter(i=>[i.renewal_id,i.original_order_id,i.full_name,i.business_name].some(v=>v.toLowerCase().includes(q))),[renewals,q]);
 const visibleLeads=useMemo(()=>leads.filter(i=>[i.full_name,i.email,i.phone,i.message].some(v=>v.toLowerCase().includes(q))),[leads,q]);
 const tabs=[{id:'analytics' as Tab,label:isRTL?'التحليلات':'Analytics',icon:BarChart3},{id:'subscribers' as Tab,label:isRTL?'المشتركين':'Subscribers',icon:ShoppingCart},{id:'renewals' as Tab,label:isRTL?'التجديدات':'Renewals',icon:RefreshCw},{id:'leads' as Tab,label:isRTL?'العملاء المحتملين':'Leads',icon:Users}];
 const labels:Record<string,string>={pending:isRTL?'قيد الانتظار':'Pending',active:isRTL?'نشط':'Active',suspended:isRTL?'معلق':'Suspended',expired:isRTL?'منتهي':'Expired',renewed:isRTL?'مجدد':'Renewed',didnt_renew:isRTL?'لم يجدد':"Didn't Renew",fake_order:isRTL?'طلب وهمي':'Fake Order',received:isRTL?'مستلم':'Received',in_progress:isRTL?'قيد التنفيذ':'In Progress',delivered:isRTL?'تم التسليم':'Delivered',live:isRTL?'مباشر':'Live',disabled:isRTL?'معطل':'Disabled',maintenance:isRTL?'صيانة':'Maintenance',paused:isRTL?'متوقف':'Paused',confirmed:isRTL?'مؤكد':'Confirmed',rejected:isRTL?'مرفوض':'Rejected',new:isRTL?'جديد':'New',contacted:isRTL?'تم التواصل':'Contacted',archived:isRTL?'مؤرشف':'Archived'};
 const statusLabel=(v:string)=>labels[v]??v; const openWhatsApp=(n:string)=>window.open(`https://wa.me/${n.replace(/\D/g,'')}`,'_blank','noopener,noreferrer');
 return <div className={`min-h-screen bg-background ${isRTL?'font-cairo':'font-sans'}`} dir={isRTL?'rtl':'ltr'}>
   <header className="lg:hidden fixed inset-x-0 top-0 z-50 border-b border-border bg-background/90 backdrop-blur-md"><div className="flex items-center justify-between p-4"><Button variant="ghost" size="icon" onClick={()=>setSidebarOpen(v=>!v)} aria-label={isRTL?'القائمة':'Menu'}>{sidebarOpen?<X/>:<Menu/>}</Button><img src={logoAsset} alt="Core Studios" className="h-7 w-auto"/><LanguageSwitcher/></div></header>
   <aside className={`fixed top-0 ${isRTL?'right-0 border-l':'left-0 border-r'} z-40 h-full w-64 border-border bg-sidebar transition-transform duration-300 ${sidebarOpen?'translate-x-0':isRTL?'translate-x-full':'-translate-x-full'} lg:translate-x-0`}><div className="flex h-full flex-col"><div className="border-b border-sidebar-border p-6"><img src={logoAsset} alt="Core Studios" className="h-8 w-auto"/><p className="mt-3 font-mono text-xs uppercase text-sidebar-foreground/60">{isRTL?'لوحة العمل':'Work dashboard'}</p></div><nav className="flex-1 space-y-2 p-4">{tabs.map(i=><Button key={i.id} variant="ghost" onClick={()=>{setTab(i.id);setSidebarOpen(false)}} className={`w-full justify-start gap-3 ${isRTL?'flex-row-reverse':''} ${tab===i.id?'bg-sidebar-accent text-sidebar-accent-foreground':'text-sidebar-foreground/80'}`}><i.icon className="size-5"/>{i.label}</Button>)}</nav><div className="space-y-3 border-t border-sidebar-border p-4"><div className="hidden lg:block"><LanguageSwitcher/></div><Button variant="outline" onClick={()=>navigate('/')} className={`w-full justify-start gap-2 ${isRTL?'flex-row-reverse':''}`}><Home className="size-5"/>{isRTL?'العودة للموقع':'Back to Website'}</Button><Button variant="ghost" onClick={()=>void supabase.auth.signOut()} className={`w-full justify-start gap-2 text-destructive hover:text-destructive ${isRTL?'flex-row-reverse':''}`}><LogOut className="size-5"/>{isRTL?'تسجيل الخروج':'Sign Out'}</Button></div></div></aside>
  {sidebarOpen&&<button type="button" className="fixed inset-0 z-30 bg-background/80 lg:hidden" onClick={()=>setSidebarOpen(false)} aria-label={isRTL?'إغلاق القائمة':'Close menu'}/>} 
   <main className={`${isRTL?'lg:mr-64':'lg:ml-64'} min-h-screen pt-16 lg:pt-0`}><div className="p-4 sm:p-6 lg:p-8">{tab==='analytics'?<AnalyticsDashboard/>:<div className="space-y-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div className={isRTL?'text-right':''}><p className="mb-2 font-mono text-xs uppercase text-muted-foreground">{isRTL?'للعرض فقط':'Read only'}</p><h1 className="text-2xl font-bold">{tabs.find(i=>i.id===tab)?.label}</h1></div><div className="relative w-full sm:w-80"><Search className={`absolute top-1/2 -translate-y-1/2 size-4 text-muted-foreground ${isRTL?'right-3':'left-3'}`}/><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder={isRTL?'بحث...':'Search...'} className={isRTL?'pr-10 text-right':'pl-10'} dir={isRTL?'rtl':'ltr'}/></div></div><div className="overflow-x-auto border border-border bg-card">{loading?<div className="p-12 text-center text-muted-foreground">{isRTL?'جاري التحميل...':'Loading...'}</div>:tab==='subscribers'?<OrdersTable items={visibleOrders} isRTL={isRTL} dateLocale={dateLocale} statusLabel={statusLabel} setDetail={setDetail} setReceipt={setReceipt} openWhatsApp={openWhatsApp}/>:tab==='renewals'?<RenewalsView items={visibleRenewals} isRTL={isRTL} dateLocale={dateLocale} statusLabel={statusLabel} setDetail={setDetail} setReceipt={setReceipt} openWhatsApp={openWhatsApp}/>:<LeadsView items={visibleLeads} isRTL={isRTL} dateLocale={dateLocale} statusLabel={statusLabel} openWhatsApp={openWhatsApp}/>}</div></div>}</div></main>
  <Dialog open={!!receipt} onOpenChange={()=>setReceipt(null)}><DialogContent className="max-h-[85vh] max-w-[90vw] overflow-y-auto sm:max-w-lg"><DialogHeader><DialogTitle>{isRTL?'إيصال الدفع':'Payment Receipt'}</DialogTitle></DialogHeader>{receipt&&<ReceiptImage value={receipt} className="max-h-[65vh] w-full object-contain"/>}</DialogContent></Dialog>
  <RenewalDetailsDialog open={detail?.type==='renewal'} onOpenChange={()=>setDetail(null)} renewal={detail?.type==='renewal'?detail.value:null}/>
  <Dialog open={detail?.type==='order'} onOpenChange={()=>setDetail(null)}><DialogContent className="max-h-[85vh] overflow-y-auto sm:max-w-lg"><DialogHeader><DialogTitle>{isRTL?'تفاصيل الطلب':'Order Details'}</DialogTitle></DialogHeader>{detail?.type==='order'&&<div className="space-y-4 text-sm"><Info label={isRTL?'رقم الطلب':'Order ID'} value={detail.value.order_id} mono/><Info label={isRTL?'العميل':'Client'} value={detail.value.full_name}/><Info label={isRTL?'النشاط':'Business'} value={detail.value.business_name}/><Info label={isRTL?'البريد':'Email'} value={detail.value.email}/><Info label={isRTL?'الهاتف':'Phone'} value={detail.value.phone}/><Info label={isRTL?'طريقة الدفع':'Payment'} value={detail.value.payment_method||'—'}/><Info label={isRTL?'رسوم الإعداد':'Setup Fee'} value={`${detail.value.setup_fee.toLocaleString()} EGP`}/><Info label={isRTL?'الرسوم الشهرية':'Monthly Fee'} value={`${detail.value.monthly_fee.toLocaleString()} EGP`}/>{detail.value.website_requirements&&<div className="border-t border-border pt-4"><span className="text-muted-foreground">{isRTL?'متطلبات الموقع':'Website Requirements'}</span><p className="mt-2 whitespace-pre-wrap">{detail.value.website_requirements}</p></div>}</div>}</DialogContent></Dialog>
 </div>
};

type Shared={isRTL:boolean;dateLocale:typeof ar;statusLabel:(v:string)=>string;setDetail:(v:Detail)=>void;setReceipt:(v:string)=>void;openWhatsApp:(v:string)=>void};
const Actions=({receipt,onDetails,onReceipt,onWhatsApp,isRTL}:{receipt:string|null;onDetails:()=>void;onReceipt:()=>void;onWhatsApp:()=>void;isRTL:boolean})=><div className="flex gap-1"><Button variant="ghost" size="icon" onClick={onDetails} title={isRTL?'التفاصيل':'Details'}><FileText className="size-4"/></Button>{receipt&&<Button variant="ghost" size="icon" onClick={onReceipt} title={isRTL?'الإيصال':'Receipt'}><Eye className="size-4"/></Button>}<Button variant="ghost" size="icon" onClick={onWhatsApp} title="WhatsApp"><MessageCircle className="size-4"/></Button></div>;
const OrdersTable=({items,isRTL,dateLocale,statusLabel,setDetail,setReceipt,openWhatsApp}:Shared&{items:Order[]})=><Table><TableHeader><TableRow>{['Order ID','Client','Business','Date','Subscription','Project','Website','View'].map((v,i)=><TableHead key={v}>{isRTL?['رقم الطلب','العميل','النشاط','التاريخ','الاشتراك','المشروع','الموقع','عرض'][i]:v}</TableHead>)}</TableRow></TableHeader><TableBody>{items.length===0?<Empty cols={8} isRTL={isRTL}/>:items.map(o=><TableRow key={o.id}><TableCell className="font-mono text-xs">{o.order_id}</TableCell><TableCell><b>{o.full_name}</b><small className="block text-muted-foreground">{o.phone}</small></TableCell><TableCell>{o.business_name}</TableCell><TableCell>{format(new Date(o.created_at),'PP',{locale:dateLocale})}</TableCell><TableCell><Badge variant="outline">{statusLabel(o.subscription_status)}</Badge></TableCell><TableCell><Badge variant="outline">{statusLabel(o.project_status)}</Badge></TableCell><TableCell><Badge variant="outline">{statusLabel(o.website_status)}</Badge></TableCell><TableCell><Actions receipt={o.receipt_url} onDetails={()=>setDetail({type:'order',value:o})} onReceipt={()=>o.receipt_url&&setReceipt(o.receipt_url)} onWhatsApp={()=>openWhatsApp(o.whatsapp)} isRTL={isRTL}/></TableCell></TableRow>)}</TableBody></Table>;
const RenewalsView=({items,isRTL,dateLocale,statusLabel,setDetail,setReceipt,openWhatsApp}:Shared&{items:Renewal[]})=><Table><TableHeader><TableRow>{['Renewal ID','Original Order','Client','Date','Status','View'].map((v,i)=><TableHead key={v}>{isRTL?['رقم التجديد','الطلب الأصلي','العميل','التاريخ','الحالة','عرض'][i]:v}</TableHead>)}</TableRow></TableHeader><TableBody>{items.length===0?<Empty cols={6} isRTL={isRTL}/>:items.map(r=><TableRow key={r.id}><TableCell className="font-mono text-xs">{r.renewal_id}</TableCell><TableCell className="font-mono text-xs">{r.original_order_id}</TableCell><TableCell><b>{r.full_name}</b><small className="block text-muted-foreground">{r.business_name}</small></TableCell><TableCell>{format(new Date(r.created_at),'PP',{locale:dateLocale})}</TableCell><TableCell><Badge variant="outline">{statusLabel(r.status)}</Badge></TableCell><TableCell><Actions receipt={r.receipt_url} onDetails={()=>setDetail({type:'renewal',value:r})} onReceipt={()=>r.receipt_url&&setReceipt(r.receipt_url)} onWhatsApp={()=>openWhatsApp(r.whatsapp)} isRTL={isRTL}/></TableCell></TableRow>)}</TableBody></Table>;
const LeadsView=({items,isRTL,dateLocale,statusLabel,openWhatsApp}:{items:Lead[];isRTL:boolean;dateLocale:typeof ar;statusLabel:(v:string)=>string;openWhatsApp:(v:string)=>void})=><Table><TableHeader><TableRow>{['Name','Email','Phone','Message','Status','Date','Contact'].map((v,i)=><TableHead key={v}>{isRTL?['الاسم','البريد','الهاتف','الرسالة','الحالة','التاريخ','تواصل'][i]:v}</TableHead>)}</TableRow></TableHeader><TableBody>{items.length===0?<Empty cols={7} isRTL={isRTL}/>:items.map(l=><TableRow key={l.id}><TableCell className="font-medium">{l.full_name}</TableCell><TableCell>{l.email}</TableCell><TableCell>{l.phone}</TableCell><TableCell className="max-w-xs whitespace-normal">{l.message}</TableCell><TableCell><Badge variant="outline">{statusLabel(l.status)}</Badge></TableCell><TableCell>{format(new Date(l.created_at),'PP',{locale:dateLocale})}</TableCell><TableCell><Button variant="ghost" size="icon" onClick={()=>openWhatsApp(l.whatsapp)} title="WhatsApp"><MessageCircle className="size-4"/></Button></TableCell></TableRow>)}</TableBody></Table>;
const Empty=({cols,isRTL}:{cols:number;isRTL:boolean})=><TableRow><TableCell colSpan={cols} className="py-10 text-center text-muted-foreground">{isRTL?'لا توجد نتائج':'No results found'}</TableCell></TableRow>;
const Info=({label,value,mono=false}:{label:string;value:string;mono?:boolean})=><div className="flex items-start justify-between gap-4 border-b border-border pb-3"><span className="text-muted-foreground">{label}</span><span className={`${mono?'font-mono':'font-medium'} text-end`}>{value}</span></div>;
export default WorkDashboard;
